#!/bin/bash

network_name="retrowave"
image_name="retrowave-air"
container_name="${image_name}-1"

docker rm -f ${container_name}

docker run \
  -d \
  --restart always \
  --name ${container_name} \
  --network ${network_name} \
  --dns-opt 'ndots:1' \
  -v retrowave-air-data:/data \
  ${image_name}
